apiVersion: v1                         # Kubernetes API 버전 지정
kind: Namespace                        # Namespace Resource 생성

metadata:                              # Namespace 메타데이터 영역
  name: git-k8s                        # Git 연계 실습용 Namespace 이름 지정
